Repository yaretzj/ChoreCenter, pull requests merged in 2021-05, with the labels that each got.

#39 Updated README and wiki for documentation
  README.md
Labels: documentation, high-priority

#53 Fixed reward history model naming error
  Backend/models/response_models.py
Labels: bug

#55 Add frontend tests and updated Actions workflow for emulator tests
  .github/workflows/gradle.yml
  Android/ChoreCenterApp/app/src/androidTest/java/com/cse403chorecenter/chorecenterapp/ChooseAccountTypeTest.java
  Android/ChoreCenterApp/app/src/main/res/layout/activity_choose_account_type.xml
  Android/ChoreCenterApp/app/src/test/java/com/cse403chorecenter/chorecenterapp/VerifyChoreTest.java
  Android/ChoreCenterApp/build.gradle
  Android/ChoreCenterApp/gradle/wrapper/gradle-wrapper.properties
Labels: frontend

#59 logo, complete chore, redeem reward designs
  Android/ChoreCenterApp/app/src/main/ic_launcher-playstore.png
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/KidNavigation.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ui/redeem_reward/RedeemRewardFragment.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ui/redeem_reward/RedeemRewardRecyclerViewAdapter.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ui/submit_chore/SubmitChoreFragment.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ui/submit_chore/SubmitChoreRecyclerViewAdapter.java
  Android/ChoreCenterApp/app/src/main/res/drawable/ic_launcher_background.xml
  Android/ChoreCenterApp/app/src/main/res/layout/fragment_redeem_reward.xml
  Android/ChoreCenterApp/app/src/main/res/layout/fragment_submit_chore.xml
  Android/ChoreCenterApp/app/src/main/res/layout/text_row_chore_item.xml
  Android/ChoreCenterApp/app/src/main/res/layout/text_row_reward_item.xml
  Android/ChoreCenterApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/ChoreCenterApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/ChoreCenterApp/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Android/ChoreCenterApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Android/ChoreCenterApp/app/src/main/res/values/ic_launcher_background.xml
Labels: frontend

#65 Updates to Android repository
  .github/workflows/gradle.yml
  Android/ChoreCenterApp/.idea/.gitignore
  Android/ChoreCenterApp/.idea/.name
  Android/ChoreCenterApp/.idea/gradle.xml
  Android/ChoreCenterApp/.idea/jarRepositories.xml
  Android/ChoreCenterApp/.idea/markdown-navigator-enh.xml
  Android/ChoreCenterApp/.idea/markdown-navigator.xml
  Android/ChoreCenterApp/.idea/misc.xml
  Android/ChoreCenterApp/.idea/vcs.xml
  Android/ChoreCenterApp/app/src/androidTest/java/com/cse403chorecenter/chorecenterapp/ChooseAccountTypeTest.java
  Android/ChoreCenterApp/app/src/androidTest/java/com/cse403chorecenter/chorecenterapp/CreateChoreTest.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ChooseAccountType.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/KidSignup.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/MainActivity.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ParentSignup.java
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/UserLogin.java
  Android/ChoreCenterApp/app/src/main/res/layout/activity_parent_signup.xml
  Android/ChoreCenterApp/app/src/main/res/values/strings.xml
  Android/ChoreCenterApp/build.gradle
  Android/README.md
Labels: documentation, frontend

#76 Comments for app.py added
  Backend/app.py
Labels: documentation

#89 Bug in Child Complete Chore Fix
  Android/ChoreCenterApp/app/src/main/java/com/cse403chorecenter/chorecenterapp/ui/submit_chore/SubmitChoreRecyclerViewAdapter.java
Labels: backend, bug, high-priority
